# Author: watsonryan
# Purpose: Strict FP and optional sanitizer/runtime flags.

function(hwm14_apply_strict_fp_flags target_name)
  if(MSVC)
    target_compile_options(${target_name} PRIVATE /fp:precise)
  else()
    target_compile_options(${target_name} PRIVATE -fno-fast-math -ffp-contract=off)
  endif()
endfunction()

function(hwm14_apply_runtime_flags target_name)
  if(HWM14_ENABLE_PROFILE)
    if(MSVC)
      target_compile_options(${target_name} PRIVATE /O2 /Zi)
    else()
      target_compile_options(${target_name} PRIVATE -O3 -g -fno-omit-frame-pointer)
    endif()
  endif()

  if(HWM14_SANITIZER STREQUAL "address")
    if(NOT MSVC)
      target_compile_options(${target_name} PRIVATE -fsanitize=address -fno-omit-frame-pointer -g)
      target_link_options(${target_name} PRIVATE -fsanitize=address)
    endif()
  elseif(HWM14_SANITIZER STREQUAL "undefined")
    if(NOT MSVC)
      target_compile_options(${target_name} PRIVATE -fsanitize=undefined -fno-omit-frame-pointer -g)
      target_link_options(${target_name} PRIVATE -fsanitize=undefined)
    endif()
  elseif(HWM14_SANITIZER STREQUAL "thread")
    if(NOT MSVC)
      target_compile_options(${target_name} PRIVATE -fsanitize=thread -fno-omit-frame-pointer -g)
      target_link_options(${target_name} PRIVATE -fsanitize=thread)
    endif()
  endif()
endfunction()
